[package]
name = "flickr2goog"
version = "0.1.0"
authors = ["haxney <dan@haxney.org>"]

[dependencies]
zip = "0.5.0"
rusqlite = "0.15.0"
diesel = { version = "1.0.0", features = ["sqlite"] }
dotenv = "0.9.0"
