[package]
name = "photo_dump_upload"
version = "0.1.0"
authors = ["Daniel Hackney <hackney@google.com>"]

[dependencies]
zip = "0.5.0"
rusqlite = "0.15.0"
diesel = { version = "1.0.0", features = ["sqlite"] }
dotenv = "0.9.0"
